name: E2E Milti-Browser Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  # Testes Chromium  
  tests-chromium:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v5

    - name: Node Setup
      uses: actions/setup-node@v5
      with:
        node-version: 22

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium

    - name: Run E2E tests
      run: npx playwright test --project=chromium
      
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-chromium
        path: playwright-report/
        retention-days: 30

  # Testes Firefox
  tests-firefox:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v5

    - name: Node Setup
      uses: actions/setup-node@v5
      with:
        node-version: 22

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps firefox

    - name: Run E2E tests
      run: npx playwright test --project=firefox
      
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-firefox
        path: playwright-report/
        retention-days: 30

  # Tests Webkit = Safari
  tests-webkit:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v5

    - name: Node Setup
      uses: actions/setup-node@v5
      with:
        node-version: 22

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps webkit

    - name: Run E2E tests
      run: npx playwright test --project=webkit
      
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-webkit
        path: playwright-report/
        retention-days: 30
   